In [51]:
import pandas as pd
import numpy as np
import seaborn as sns

In [52]:
df = pd.read_csv("email.csv")

df = df[["Message", "Category"]].rename(columns={
    "Message": "text",
    "Category": "spam"
})
df["spam"] = df["spam"].map({"ham": 0, "spam": 1})
df.dropna(subset=["spam"], inplace=True) # Drop rows where 'spam' became NaN
df["spam"] = df["spam"].astype(int)

In [53]:
df.head()

                                                text  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [54]:
df['spam'].value_counts()

spam
0    4825
1     747
Name: count, dtype: int64

In [55]:
df.drop_duplicates(inplace=True)

In [56]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [57]:
df['spam'].value_counts()

spam
0    4516
1     641
Name: count, dtype: int64

In [58]:
x = df.text.values
y = df.spam.values

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [61]:
from sklearn.feature_extraction.text import CountVectorizer

In [62]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)

In [63]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [64]:
from sklearn.naive_bayes import MultinomialNB

In [66]:
model = MultinomialNB()
model.fit(x_train, ytrain)

MultinomialNB()

In [68]:
x_test = cv.transform(xtest)

In [71]:
model.score(x_test, ytest)*100

98.15891472868216

In [72]:
emails = ['hey I am looking for a ml tutorial in bangla language','hey,you win a iphone x giveway for free please fill the form']

In [73]:
cv_emails = cv.transform(emails)

In [74]:
model.predict(cv_emails)

array([0, 1])